name: predict_pv_yield
channels:
  - pytorch
  - numba
  - pvlib
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - jupyterlab
  - xarray
  - dask
  - zarr
  - cfgrib
  - netcdf4
  - scikit-learn
  - numba
  - gcsfs
  - cartopy
  - seaborn
  - rasterio
  - pvlib
  - pytorch
  - pytest
  - pathlib
  - gsutil